config/routes.rb
Rails.application.routes.draw do
  get 'weapons/index'
  root 'weapons#index'
  devise_for :users
  resources :weapons

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/weapon.rb
class Weapon < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/weapons_controller.rb
class WeaponsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_weapon, only: [:show, :edit, :update, :destroy]

  # GET /weapons
  # GET /weapons.json
  def index
    @weapons = Weapon.all
  end

  # GET /weapons/1
  # GET /weapons/1.json
  def show
  end

  # GET /weapons/new
  def new
    @weapon = Weapon.new
  end

  # GET /weapons/1/edit
  def edit
  end

  # POST /weapons
  # POST /weapons.json
  def create
    @weapon = Weapon.new(weapon_params)

    respond_to do |format|
      if @weapon.save
        format.html { redirect_to @weapon, notice: 'Weapon was successfully created.' }
        format.json { render :show, status: :created, location: @weapon }
      else
        format.html { render :new }
        format.json { render json: @weapon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weapons/1
  # PATCH/PUT /weapons/1.json
  def update
    respond_to do |format|
      if @weapon.update(weapon_params)
        format.html { redirect_to @weapon, notice: 'Weapon was successfully updated.' }
        format.json { render :show, status: :ok, location: @weapon }
      else
        format.html { render :edit }
        format.json { render json: @weapon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weapons/1
  # DELETE /weapons/1.json
  def destroy
    @weapon.destroy
    respond_to do |format|
      format.html { redirect_to weapons_url, notice: 'Weapon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weapon
      @weapon = Weapon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def weapon_params
      params.require(:weapon).permit(:name, :caliber, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def markdown(text)
    return '' unless text.present?
    @options ||= {
		hard_wrap: true,
        autolink: true,
        link_attributes: {rel: 'nofollow', target: "_blank"}
    }
    @markdown ||= Redcarpet::Markdown.new(Redcarpet::Render::HTML, @options)
    @markdown.render(text).html_safe
	end


end

app/helpers/weapons_helper.rb
module WeaponsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Weapons</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/weapons/_form.html.erb
<%= form_for(@weapon) do |f| %>
  <% if @weapon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@weapon.errors.count, "error") %> prohibited this weapon from being saved:</h2>

      <ul>
      <% @weapon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :caliber %><br>
    <%= f.text_field :caliber %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/weapons/edit.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Sklep komputerowy</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
	<nav class="navbar navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<ul class="nav navbar-nav navbar-right">
					<li><%= link_to "Weapons", weapons_path, :class => 'navbar-link'  %></li>
				</ul>
			</div>
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav navbar-right">
				<% if user_signed_in? %>
					<li>Logged in as <strong><%= current_user.email %></strong>.</li>
					<li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
					<li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
				<% else %>
					<li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> </li>
					<li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
				<% end %>
				</ul>
			</div>	
		</div>
	</nav>
	
	<div class="container">
		<div class="col-sm-3">
			<br/>
<br/>
<br/>
			<div class="panel panel-default" style="margin-top: 20px;">
				<div class="panel-heading">
					Opcje
				</div>
				<ul class="nav nav-pills nav-stacked" style="margin: 0">
					<li role="presentation"><%= link_to "Show weapons", weapons_path, :class => 'navbar-link'  %></li>
				</ul>
			</div>
		</div>	
		<div class="col-sm-9 padding-top">
			</br>
			</br>
			</br>
			<h1>Editing Weapon</h1>

<%= render 'form' %>

<%= link_to 'Show', @weapon %> |
<%= link_to 'Back', weapons_path %>

		</div>	
	</div>
</body>

app/views/weapons/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Sklep komputerowy</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
	<nav class="navbar navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<ul class="nav navbar-nav navbar-right">
					<li><%= link_to "Weapons", weapons_path, :class => 'navbar-link'  %></li>
				</ul>
			</div>
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav navbar-right">
				<% if user_signed_in? %>
					<li>Logged in as <strong><%= current_user.email %></strong>.</li>
					<li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
					<li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
				<% else %>
					<li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> </li>
					<li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
				<% end %>
				</ul>
			</div>	
		</div>
	</nav>
	
	<div class="container">
		<div class="col-sm-3">
			<br/>
<br/>
<br/>
			<div class="panel panel-default" style="margin-top: 20px;">
				<div class="panel-heading">
					Opcje
				</div>
				<ul class="nav nav-pills nav-stacked" style="margin: 0">
					<li role="presentation"><%= link_to "Add new weapon", new_weapon_path, :class => 'navbar-link'  %></li>
				</ul>
			</div>
		</div>	
		<div class="col-sm-9 padding-top">
			</br>
			</br>
			</br>
			<h1>Listing Weapons</h1>

			<table border="3">
			  <thead>
				<tr>
				  <th>Name</th>
				  <th>Caliber</th>
				  <th>Description</th>
				  <th colspan="3"></th>
				</tr>
			  </thead>

			  <tbody>
				<% @weapons.each do |weapon| %>
				  <tr>
					<td><%= weapon.name %></td>
					<td><%= weapon.caliber %></td>
					<td><%= markdown weapon.description %></td>
					<td><%= link_to 'Show', weapon %></td>
					<td><%= link_to 'Edit', edit_weapon_path(weapon) %></td>
					<td><%= link_to 'Destroy', weapon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
				  </tr>
				<% end %>
			  </tbody>
			</table>

			<br>
		</div>	
	</div>
</body>

app/views/weapons/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Sklep komputerowy</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
	<nav class="navbar navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<ul class="nav navbar-nav navbar-right">
					<li><%= link_to "Weapons", weapons_path, :class => 'navbar-link'  %></li>
				</ul>
			</div>
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav navbar-right">
				<% if user_signed_in? %>
					<li>Logged in as <strong><%= current_user.email %></strong>.</li>
					<li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
					<li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
				<% else %>
					<li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> </li>
					<li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
				<% end %>
				</ul>
			</div>	
		</div>
	</nav>
	
	<div class="container">
		<div class="col-sm-3">
			<br/>
<br/>
<br/>
			<div class="panel panel-default" style="margin-top: 20px;">
				<div class="panel-heading">
					Opcje
				</div>
				<ul class="nav nav-pills nav-stacked" style="margin: 0">
					<li role="presentation"><%= link_to "Show weapons", weapons_path, :class => 'navbar-link'  %></li>
				</ul>
			</div>
		</div>	
		<div class="col-sm-9 padding-top">
			</br>
			</br>
			</br>
			<h1>New Weapon</h1>

<%= render 'form' %>

<%= link_to 'Back', weapons_path %>
		</div>	
	</div>
</body>

app/views/weapons/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Sklep komputerowy</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
	<nav class="navbar navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<ul class="nav navbar-nav navbar-right">
					<li><%= link_to "Weapons", weapons_path, :class => 'navbar-link'  %></li>
				</ul>
			</div>
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav navbar-right">
				<% if user_signed_in? %>
					<li>Logged in as <strong><%= current_user.email %></strong>.</li>
					<li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
					<li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
				<% else %>
					<li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> </li>
					<li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
				<% end %>
				</ul>
			</div>	
		</div>
	</nav>
	
	<div class="container">
		<div class="col-sm-3">
			<br/>
			<br/>
			<br/>
			<div class="panel panel-default" style="margin-top: 20px;">
				<div class="panel-heading">
					Opcje
				</div>
				<ul class="nav nav-pills nav-stacked" style="margin: 0">
					<li role="presentation"><%= link_to "Show weapons", weapons_path, :class => 'navbar-link'  %></li>
				</ul>
			</div>
		</div>	
		<div class="col-sm-9 padding-top">
			</br>
			</br>
			</br>
			<p id="notice"><%= notice %></p>

			<p>
			  <strong>Name:</strong>
			  <%= @weapon.name %>
			</p>

			<p>
			  <strong>Caliber:</strong>
			  <%= @weapon.caliber %>
			</p>

			<p>
			  <strong>Description:</strong>
			  <%= markdown @weapon.description %>
			</p>

			<%= link_to 'Edit', edit_weapon_path(@weapon) %> |
			<%= link_to 'Back', weapons_path %>
		</div>	
	</div>
</body>